FROM node:16

# Open port 5000
EXPOSE 5000

# Set working directory
WORKDIR /usr/src/app

COPY package*.json ./

# Set environment variable
#ENV REACT_APP_BACKEND_URL=http://localhost:8080

# copy contents of current directory
RUN npm install
COPY . .
RUN npm run build
RUN npm install -g serve

CMD serve -s -l 5000 build