version: '3.8'

services:
    simple-web-service:
      image: devopsdockeruh/simple-web-service
      build: .
      ports: 
        - 127.0.0.1:8080:8080
      command: server
      container_name: simple-web-service