version: '3.8'

services:
    example-frontend:
      build:
        context: ./example-frontend
        dockerfile: Dockerfile
      ports: 
        - 127.0.0.1:5000:5000
      container_name: example-frontend

    redis:
      image: redis:6.2-alpine
      restart: unless-stopped
      ports:
        - '127.0.0.1:6379:6379'
        
    example-backend:
      build:
        context: ./example-backend
        dockerfile: Dockerfile
      ports: 
        - 127.0.0.1:8080:8080
      depends_on:
        - redis
      environment:
        REDIS_HOST: redis
      container_name: example-backend